### ISSUE TITLE
Sample of deleteNotificationn would be helpful - too abstract for the time being

### ISSUE THREAD

**Issue by RVDHOFAUDEV** [BBj-Plugins/BBjNotificationManager#2]
unable to manage the deleteNotification as recommended in the java doc...

----------------------------------------------------------------------------  optional values are : text, dismiss, title, handle, color, image, buttons, link these can be passed null() if not required and will be left out **if an eventhandle was given to the Notification it will push the event 17 which can be caught by processing event onclick: (A Notification has to be cleared manually if it was clicked, which can be performed using the eventhandle delivered by the event and the deletehandle(String handle) method**  if a timeout was given the Notification will be dismissed on the timeout count (in seconds) if a color (BBjColor) is given it will change the BackgroundColor of the Notification if an image (only BBj-conform formats can be used) is passed it will appear on the left hand side of the Notification as an Icon if Buttons are passed every Item in the List will be added as a Button in the Notification. to pass buttons simply create a java.util.ArrayList and fill it with NotificationButton Objects, provided in the Plugin to create an object call the constructor with new NotificationButton(String text, String eventhandle, int width) and put it in to the List if a link is passed, the Notification will get a little button which will redirect the user to given links ----------------------------------------------------------------------------

what string of the pushed event is mentioned? 
Can you please a sample to the demo? 
Thank you.

**Comment by Wood-ruff** [comment]
I have added an example with a little explanation in version 1.0.3 to the processevents section and a fix for an issue related to the deleteNotification method in 1.0.4 it should work as intended now
