### ISSUE TITLE
Small text corrections in the readme

### ISSUE THREAD

**Issue by RalphLance** [BBj-Plugins/BBjNotificationManager#3]
Plugin that manages and displays noitifcations autonomously. (Spelling of "notifications")

Displays Notification for a chosen amount of time or infinitely and closes them down on a run out timer or a dismissbutton. (Simpler is: "Displays notifications, optionally for a chosen amount of time or until dismissed.")

**Comment by Wood-ruff** [comment]
Thanks for helping out, i have fixed it right away.
